import links from './_links';

export default [
  {
    id: 0,
    productType: 'map',
    categories: 'Одношарові мапи',
    name: 'Одношарова мапа',
    pageLink: links.productPage,
    imgAlt: 'Дерев\'яна мапа',
    descText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    basicPrice: 3000,
    sizePrices: {
      M: 0,
      L: 900,
      XL: 1500,
    },
    typePrices: {
      Prime: 0,
      'Prime planes': 300,
      'Prime flags': 500,
    },
    rate: 3.5,
  },
  {
    id: 1,
    productType: 'map',
    categories: 'Багатошарові мапи',
    name: 'Двошарова мапа',
    pageLink: links.productPage,
    imgAlt: 'Дерев\'яна мапа',
    descText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    basicPrice: 3515,
    basicOldPrice: 3700,
    sizePrices: {
      M: 0,
      L: 900,
      XL: 1500,
    },
    typePrices: {
      Prime: 0,
      'Prime planes': 300,
      'Prime flags': 500,
    },
    rate: 3.7,
  },
  {
    id: 2,
    productType: 'map',
    categories: 'Мапи з підсвічуванням',
    name: 'Двошарова мапа з підсвічуванням',
    pageLink: links.productPage,
    imgAlt: 'Дерев\'яна мапа',
    descText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    basicPrice: 4050,
    basicOldPrice: 4500,
    sizePrices: {
      M: 0,
      L: 900,
      XL: 1500,
    },
    typePrices: {
      Prime: 0,
      'Prime planes': 300,
      'Prime flags': 500,
    },
    rate: 4.1,
  },
  {
    id: 3,
    productType: 'map',
    categories: 'Багатошарові мапи',
    name: 'Тришарова мапа',
    pageLink: links.productPage,
    imgAlt: 'Дерев\'яна мапа',
    descText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    basicPrice: 4500,
    basicOldPrice: 5000,
    sizePrices: {
      M: 0,
      L: 900,
      XL: 1500,
    },
    typePrices: {
      Prime: 0,
      'Prime planes': 300,
      'Prime flags': 500,
    },
    rate: 5,
  },
  {
    id: 4,
    productType: 'map',
    categories: 'Мапи з підсвічуванням',
    name: 'Тришарова мапа з підсвічуванням',
    pageLink: links.productPage,
    imgAlt: 'Дерев\'яна мапа',
    descText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    basicPrice: 5130,
    basicOldPrice: 5700,
    sizePrices: {
      M: 0,
      L: 900,
      XL: 1500,
    },
    typePrices: {
      Prime: 0,
      'Prime planes': 300,
      'Prime flags': 500,
    },
    rate: 4.4,
  },
  {
    id: 5,
    productType: 'accessories',
    categories: 'Додатки до мап',
    name: 'Додатки до мап',
    pageLink: links.productPage,
    imgAlt: 'Піни з прапорами країн світу',
    descText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    basicPrice: 800,
    basicOldPrice: 1000,
    rate: 4,
  },
];
